<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="../TeamBoard.Application/TeamBoard.Application.csproj"/><ProjectReference Include="../TeamBoard.Domain/TeamBoard.Domain.csproj"/><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3"/><PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12"/><PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5"/></ItemGroup></Project>
