import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, ArrowRight, Check, CheckCheck, ChevronDown, X, Map, Focus, NotebookPen, Copy, Terminal, Route, ArrowUpRight, BookOpen, Menu, Download, Circle, RotateCcw, ChevronLeft, ExternalLink, Code2 } from 'lucide-react';
import { marked } from 'marked';
import { modules, lessons } from '../../content/course.js';
import './style.css';
import { InteractiveLab } from './labs.jsx';

const KEY='t3lm-dotnet-v1';
function read(){try { const v=JSON.parse(localStorage.getItem(KEY)); return v&&typeof v==='object'?v:{}; }catch{return {};}}
const initial=read();
const stages=[['HTTP','طلب يصل إلى الخادم','GET /users/42','العميل يرسل method ومسارًا وheaders. يتولى Kestrel استقبال HTTP.'],['Middleware','سلوك يحيط بالطلب','await next(context);','كل middleware يمكنه تنفيذ عمل قبل التالي وبعده، أو إنهاء الطلب مبكرًا.'],['Endpoint','اختيار الكود المناسب','MapGet("/users/{id:int}", ...)','Routing يطابق المسار، ثم يُربط id بالقيمة 42 وتُستدعى الدالة.'],['Service','قاعدة العمل في مكانها','users.FindAsync(42, ct)','الخدمة تنفّذ قاعدة العمل. DI يوفّر لها dependencies المسجلة.'],['Database','البيانات المطلوبة فقط','SELECT id, name FROM users\nWHERE id = 42;','EF Core يترجم الاستعلام القابل للترجمة إلى SQL ثم يبني النتيجة.'],['Response','النتيجة تعود إلى العميل','200 OK\n{ "id": 42, "name": "Nora" }','الـ serializer يكتب JSON؛ ثم يعود التحكم خلال middleware بالترتيب العكسي.']];
function Rich({text}){return <div className="prose" dangerouslySetInnerHTML={{__html:marked.parse(text||'')}}/>;}
function Code({code,lang='C#'}){const [copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setCopied(false);}}return <div className="codebox"><div className="codehead"><span>{lang}</span><button onClick={copy} aria-label="نسخ الكود">{copied?<Check size={15}/>:<Copy size={15}/>}<span>{copied?'تم النسخ':'نسخ'}</span></button></div><pre dir="ltr"><code>{code}</code></pre></div>;}
function Trace(){const [active,setActive]=useState(0);return <div className="trace-lab"><div className="lab-heading"><Route size={18}/><span>تتبّع الطلب</span><small>محاكاة توضيحية</small></div><div className="trace-route" dir="ltr">{stages.map((s,i)=><button className={`trace-node ${active===i?'active':''} ${active>i?'passed':''}`} key={s[0]} onClick={()=>setActive(i)} aria-pressed={active===i}><span className="node-dot">{active>i?<Check size={11}/>:String(i+1).padStart(2,'0')}</span><span>{s[0]}</span>{i<5&&<span className="connector"/>}</button>)}</div><div className="trace-detail"><span className="eyebrow">المحطة الحالية</span><h3>{stages[active][1]}</h3><pre dir="ltr">{stages[active][2]}</pre><p>{stages[active][3]}</p></div><button className="trace-next" onClick={()=>setActive((active+1)%6)}>{active===5?'أعد الرحلة':'مرّر الطلب للمحطة التالية'}<ArrowLeft size={16}/></button></div>;}
function Quiz({question}){const [answer,setAnswer]=useState(null);return <div className="quiz"><span className="eyebrow">جرّب تفسيرك</span><h3>{question.text}</h3><div className="options">{question.options.map((o,i)=><button key={o} className={answer===i?(i===question.correct?'correct':'selected'):''} onClick={()=>setAnswer(i)}><span>{answer===i&&i===question.correct?<Check size={16}/>:String.fromCharCode(65+i)}</span>{o}</button>)}</div>{answer!==null&&<p className={`feedback ${answer===question.correct?'is-correct':'is-incorrect'}`} role="status">{answer===question.correct?'بالضبط. ':'خلّنا نتتبّع السبب. '}{question.explanation}</p>}</div>;}
function App(){
const hash=decodeURIComponent(location.hash.slice(1)).split('/');
const start=lessons.find(l=>l.id===hash[0])||lessons.find(l=>l.id===initial.lesson)||lessons[0];
const [home,setHome]=useState(!location.hash || location.hash==='#home');
const [lessonId,setLesson]=useState(start.id),[step,setStep]=useState(Math.min(Math.max(0,Math.trunc(Number(hash[0]&&hash[0]!=='home'?(hash[1]??0):initial.step)||0)),start.steps.length-1));
const [done,setDone]=useState(Array.isArray(initial.done)?initial.done.filter(x=>lessons.some(l=>l.id===x)):[]),[notes,setNotes]=useState(initial.notes&&typeof initial.notes==='object'?initial.notes:{});
const [focus,setFocus]=useState(false),[panel,setPanel]=useState(null),[mobile,setMobile]=useState(false),[finished,setFinished]=useState(false),[saveError,setSaveError]=useState(false),[mapModule,setMapModule]=useState(start.module);
const lesson=lessons.find(l=>l.id===lessonId)||lessons[0], mod=modules.find(m=>m.id===lesson.module), current=lesson.steps[step]||lesson.steps[0], idx=lessons.indexOf(lesson);
const dialog=useRef(null),lastFocus=useRef(null);
useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify({lesson:lessonId,step,done,notes}));setSaveError(false);}catch{setSaveError(true);}history.replaceState(null,'',home?'#home':`#${lessonId}/${step}`);},[lessonId,step,done,notes,home]);
useEffect(()=>{const onHash=()=>{if(location.hash==='#home'){setHome(true);return;}const [id,s]=decodeURIComponent(location.hash.slice(1)).split('/');const l=lessons.find(x=>x.id===id);if(l){setHome(false);setLesson(id);setStep(Math.min(Math.max(0,Number(s)||0),l.steps.length-1));setFinished(false);}};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[]);
useEffect(()=>{document.title=home?'مسار .NET — الرئيسية':`${lesson.title} — مسار .NET`;},[lesson,home]);
useEffect(()=>{if(panel){lastFocus.current=document.activeElement;dialog.current?.showModal();}else if(dialog.current?.open){dialog.current.close();lastFocus.current?.focus();}},[panel]);
function go(l){setHome(false);setLesson(l.id);setStep(0);setFinished(false);setPanel(null);setMobile(false);window.scrollTo({top:0});}
function next(){if(step<lesson.steps.length-1){setStep(step+1);window.scrollTo({top:0});}else{setDone([...new Set([...done,lesson.id])]);setFinished(true);window.scrollTo({top:0});}}
function backup(){const blob=new Blob([JSON.stringify({lesson:lessonId,step,done,notes},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dotnet-learning-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
return <div className={`app ${focus?'is-focus':''}`}>
<a href="#lesson-content" className="skip" onClick={e=>{e.preventDefault();document.getElementById('lesson-content')?.focus();}}>انتقل إلى الدرس</a>
<aside className={`sidebar ${mobile?'mobile-open':''}`}><div className="brand-row"><button className="brand" aria-label="الواجهة الرئيسية" onClick={()=>{setHome(true);setMobile(false);window.scrollTo({top:0});}}><span className="brand-icon"><Route size={24}/></span><div><strong>مسار <bdi>.NET</bdi></strong><span>من الطلب إلى الفريق</span></div></button><button className="mobile-close icon-button" aria-label="إغلاق القائمة" onClick={()=>setMobile(false)}><X/></button></div><div className="sidebar-separator"/><span className="side-label">أنت هنا</span><div className="module-label"><span>{mod.number}</span><div><strong>{mod.title}</strong><small>{mod.subtitle}</small></div></div><nav aria-label="دروس المحطة الحالية">{lessons.filter(l=>l.module===lesson.module).map(l=><button key={l.id} className={`lesson-link ${l.id===lessonId?'active':''}`} onClick={()=>go(l)}>{done.includes(l.id)?<CheckCheck size={17}/>:l.id===lessonId?<span className="current-dot"/>:<Circle size={13}/>}<span>{l.title}</span>{l.id===lessonId&&<ChevronLeft size={15}/>}</button>)}</nav><button className="map-button" onClick={()=>{setMapModule(lesson.module);setPanel('map');}}><Map size={18}/><span>افتح خريطة الرحلة</span><ArrowUpRight size={16}/></button><div className="sidebar-bottom"><div className="project-marker"><span className="project-square"><Code2 size={19}/></span><div><strong dir="ltr">TeamBoard API</strong><small>مشروع واحد ينمو معك</small></div></div><p>خطوة تفهمها اليوم،<br/>تبني عليها بكرة.</p><div className="version"><span dir="ltr">.NET 10 · C# 14</span><span>LTS</span></div></div></aside>
<div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-button menu-button" aria-label="فتح القائمة" onClick={()=>setMobile(true)}><Menu size={20}/></button><button className="home-link" onClick={()=>{setHome(true);window.scrollTo({top:0});}}>الرئيسية</button>{!home&&<><ChevronLeft size={14}/><strong>{mod.title}</strong></>}</div><div className="top-actions"><button aria-label="دفتر التعلّم" onClick={()=>setPanel('notes')}><NotebookPen size={17}/><span>دفتر التعلّم</span></button><button aria-label={focus?'إظهار المسار':'وضع التركيز'} className={focus?'on':''} onClick={()=>{setFocus(!focus);setMobile(false);}} aria-pressed={focus}><Focus size={17}/><span>{focus?'إظهار المسار':'وضع التركيز'}</span></button></div></header>
<main id="lesson-content" tabIndex={-1}>{home?<Home lesson={lesson} step={step} done={done} go={go} resume={()=>setHome(false)} openMap={()=>setPanel('map')}/>:<><div className="session-bar"><span><span className="session-dot"/>جلسة صغيرة، فكرة واضحة</span><span><BookOpen size={14}/>{lesson.minutes} دقائق قراءة · والتطبيق على راحتك</span></div>
{finished?<section className="finish"><span className="finish-icon"><Check size={34}/></span><span className="eyebrow">شيء جديد صار واضحًا</span><h1>{lesson.gain}</h1><p>هذه نقطة توقف مناسبة. موضعك محفوظ، والخطوة التالية تنتظرك متى رجعت.</p><label htmlFor="takeaway">اكتب بطريقتك ما تريد تتذكره <small>اختياري</small></label><textarea id="takeaway" value={notes[lessonId]||''} onChange={e=>setNotes({...notes,[lessonId]:e.target.value})} placeholder="الفكرة التي أخذتها معي…"/>{idx<lessons.length-1?<button className="primary" onClick={()=>go(lessons[idx+1])}>نكمل: {lessons[idx+1].title}<ArrowLeft size={18}/></button>:<button className="primary" onClick={()=>setPanel('notes')}>افتح حصيلة الرحلة<CheckCheck size={18}/></button>}<button className="text-button" onClick={()=>setFinished(false)}>أرجع للدرس</button></section>:<><div className="lesson-heading"><div className="eyebrow"><span className="chapter-number">{mod.number}</span>{lesson.title}</div><h1>{current.title}</h1><p>{step===0?lesson.summary:current.aside||'نبقى مع الطلب نفسه، ونفتح التفصيل الذي نحتاجه الآن.'}</p></div><BuildBrief mod={mod}/><div className={`learning-grid ${current.lab?'has-lab':''}`}><article className="lesson-card" key={`${lessonId}/${step}`}><div className="card-kicker"><span className="mini-line"/>{current.question?'تثبيت الفكرة':current.task?'تطبيق على جهازك':'الفكرة'}</div><Rich text={current.body}/>{current.code&&<Code code={current.code} lang={current.lang}/>} {current.question&&<Quiz question={current.question}/>} {current.task&&<div className="task-box"><Terminal size={19}/><div><h3>جرّبها الآن</h3><Rich text={current.task}/></div></div>}{current.hint&&<details><summary>أحتاج تلميحًا <ChevronDown size={16}/></summary><Rich text={current.hint}/></details>}{current.solution&&<details><summary>قارن مع الحل المشروح <ChevronDown size={16}/></summary><Rich text={current.solution}/></details>}{current.result&&<div className="expected"><Check size={17}/><div><strong>علامة نجاح التجربة</strong><Rich text={current.result}/></div></div>}</article>{current.lab&&<aside className="companion"><Lab key={`${lessonId}-${step}`} type={current.lab}/><div className="margin-note"><span>على امتداد الرحلة</span><p>{current.aside||'نغيّر عاملًا واحدًا، ثم نتتبّع أثره. المحاكاة تشرح الفكرة؛ التنفيذ الحقيقي في مختبر جهازك.'}</p></div></aside>}</div><div className="under-lesson"><span><Route size={16}/> {lesson.gain}</span><button onClick={()=>setPanel('sources')}>مرجع هذه الخطوة <ExternalLink size={14}/></button></div></>}
</>}</main>{!home&&<footer className="study-footer"><div className="footer-state"><span>{saveError?'تعذّر الحفظ؛ صدّر دفتر التعلّم': 'موضعك محفوظ على هذا المتصفح'}</span><div className="step-dots" aria-label={`اللقطة ${step+1} من ${lesson.steps.length}`}>{lesson.steps.map((_,i)=><button key={i} aria-label={`اللقطة ${i+1}`} aria-current={step===i?'step':undefined} className={i===step?'active':i<step?'past':''} onClick={()=>{setStep(i);setFinished(false);window.scrollTo({top:0});}}/>)}</div></div><div className="footer-actions"><button className="back-button" disabled={step===0&&!finished} onClick={()=>{if(finished)setFinished(false);else setStep(step-1);window.scrollTo({top:0});}} aria-label="اللقطة السابقة"><ArrowRight size={19}/></button>{!finished&&<button className="primary" onClick={next}>{step===lesson.steps.length-1?'أخذت الفكرة':'فهمتها، نكمل'}<ArrowLeft size={18}/></button>}</div></footer>}</div>
<dialog ref={dialog} onCancel={()=>setPanel(null)} onClick={e=>{if(e.target===dialog.current)setPanel(null);}}><div className="dialog-header"><div><span className="eyebrow">مسار .NET</span><h2>{panel==='map'?'خريطة الرحلة':panel==='notes'?'دفتر التعلّم':'من المصدر'}</h2></div><button className="icon-button" onClick={()=>setPanel(null)} aria-label="إغلاق النافذة"><X size={22}/></button></div>{panel==='map'&&<><p className="dialog-intro">الخريطة كاملة هنا وقت ما تحتاجها. تقدر تدخل أي درس مباشرة، وتكمل بالسرعة التي تناسبك.</p><div className="map-list">{modules.map(m=><section key={m.id}><button className="map-module" aria-expanded={mapModule===m.id} onClick={()=>setMapModule(mapModule===m.id?null:m.id)}><span>{m.number}</span><strong>{m.title}<small>{m.subtitle}</small></strong><small>{m.time}</small><ChevronDown size={18}/></button>{mapModule===m.id&&<div className="map-lessons">{lessons.filter(l=>l.module===m.id).map(l=><button key={l.id} onClick={()=>go(l)}>{done.includes(l.id)?<Check size={16}/>:<Circle size={12}/>}<span>{l.title}</span><ArrowLeft size={16}/></button>)}</div>}</section>)}</div></>}{panel==='notes'&&<><p className="dialog-intro">ما صار واضحًا، والأفكار التي كتبتها. تُحفظ محليًا على هذا المتصفح.</p><label className="note-label" htmlFor="lesson-note">ملاحظتك على «{lesson.title}»</label><textarea id="lesson-note" value={notes[lessonId]||''} onChange={e=>setNotes({...notes,[lessonId]:e.target.value})} placeholder="اشرح الفكرة لنفسك، أو اترك سؤالًا ترجع له…"/><div className="gains">{done.length===0?<p>كل درس تنهيه يترك هنا فكرة تعرف تستخدمها.</p>:done.map(id=>{const l=lessons.find(l=>l.id===id);return <div key={id}><CheckCheck size={18}/><div><button onClick={()=>go(l)}>{l.gain}</button>{notes[id]&&<p>{notes[id]}</p>}</div></div>;})}</div><button className="secondary" onClick={backup}><Download size={16}/>تصدير الملاحظات والتقدّم</button></>}{panel==='sources'&&<><p className="dialog-intro">المثال في الدرس يشرح علاقة محددة. ارجع للتوثيق لتفاصيل السلوك والخيارات.</p>{lesson.sources?.map(([title,url])=><a className="source-link" key={url} href={url} target="_blank" rel="noreferrer"><span dir="ltr">{title}</span><ExternalLink size={17}/></a>)}<p className="reference-note">الإصدار المستهدف: .NET 10 وC# 14. الأمثلة التي لا يذكر فيها ملف كامل هي مقتطفات تُقرأ داخل سياق الدرس.</p></>}</dialog></div>;}
function HomeArchitecture({go}){return <div className="home-architecture"><span className="eyebrow">خريطة المشروع</span><p>نفس القلب، وأطراف قابلة للتبديل.</p><div className="architecture-inputs" dir="ltr"><button onClick={()=>go(lessons.find(l=>l.id==='controller'))}>HTTP<small>Controller</small></button><span>↓</span><button onClick={()=>go(lessons.find(l=>l.id==='unit-tests'))}>Test<small>Another entry</small></button></div><button className="architecture-core" onClick={()=>go(lessons.find(l=>l.id==='ports-adapters'))}><span>Application + Domain</span><strong>قاعدة التعيين</strong><small>المهمة ← العضوية ← القرار</small></button><div className="architecture-outputs" dir="ltr"><button onClick={()=>go(lessons.find(l=>l.id==='dbcontext'))}><span>IBoardStore</span><strong>PostgreSQL</strong></button><button onClick={()=>go(lessons.find(l=>l.id==='httpclient'))}><span>IAssignmentNotifier</span><strong>HTTP / Log</strong></button></div><small className="architecture-caption">اختر جزءًا لتفتح موضعه في الرحلة</small></div>;}
function BuildBrief({mod}){return <details className="build-brief"><summary><span><Code2 size={16}/>في مشروعك: {mod.build||mod.title}</span><ChevronDown size={16}/></summary><p>{mod.outcome}</p><div className="build-links"><a href={`./stages/${mod.stage}.zip`} download><Download size={15}/>ملفات هذه المحطة</a><a href={`./stages/${mod.stage}.html`} target="_blank" rel="noreferrer">خطوات التعديل والملفات<ExternalLink size={14}/></a></div><small>اكمل داخل مجلد TeamBoard نفسه. الحزمة تحتوي الملفات المجهزة وخطواتك والحل للمقارنة؛ ابدأ بالتكليف.</small></details>;}
function Home({lesson,step,done,go,resume,openMap}){return <section className="home"><div className="home-intro"><div className="home-intro-copy"><span className="eyebrow">رحلة TeamBoard · مشروع واحد</span><h1>نبني TeamBoard.<br/><span>جزءًا بعد جزء.</span></h1><p>لوحة عمل لفريق صغير. من الرسم الجاهز إلى تغيير تبنيه بنفسك.<br/>كل المحطات مفتوحة، والمشروع يكبر معك.</p><div className="home-downloads"><a className="primary" href="./teamboard-starter.zip" download><Download size={17}/>حمّل البداية الجاهزة</a><button className="text-button" onClick={()=>go(lessons.find(l=>l.id==='solution'))}>افهم الهيكل السداسي<ArrowLeft size={16}/></button></div><div className="home-version" dir="ltr"><span>.NET 10</span><span>C# 14</span><span>TeamBoard API</span></div></div><HomeArchitecture go={go}/></div><div className="resume-card"><div><span className="eyebrow">{done.length||step?'نقطة رجوعك':'مدخل مقترح'}</span><h2>{lesson.title}</h2><p>{lesson.steps[step]?.title}</p></div><button className="primary" onClick={resume}>{done.length||step?'أكمل من مكاني':'افتح الدرس'}<ArrowLeft size={18}/></button></div><div className="home-section-head"><div><span className="eyebrow">اختر محطتك</span><h2>رحلة البناء، على نفس المشروع.</h2></div><button className="text-button" onClick={openMap}><Map size={17}/>كل الدروس</button></div><div className="station-grid">{modules.map(m=>{const ls=lessons.filter(l=>l.module===m.id);return <button className="station" key={m.id} onClick={()=>go(ls.find(l=>!done.includes(l.id))||ls[0])}><span className="station-num">{m.number}</span><div><h3>{m.build||m.title}</h3><p>{m.outcome||m.subtitle}</p><span>{ls.some(l=>done.includes(l.id))?'عندك أساس هنا':'استكشف المحطة'}</span></div><ArrowUpRight size={20}/></button>;})}</div><div className="home-project"><Code2 size={28}/><div><h2>من تعيين المهمة إلى إشعار الفريق</h2><p>سداسي بحجم الحاجة: منافذ واضحة، PostgreSQL، وHTTP. بلا طبقات زائدة.</p></div><button className="secondary" onClick={()=>go(lessons.find(l=>l.id==='graduation')||lessons[0])}>افتح تحدّي المشروع<ArrowLeft size={16}/></button></div></section>;}
function Lab({type}) { return type==='trace'?<Trace/>:<InteractiveLab key={type} type={type}/>; }
createRoot(document.getElementById('root')).render(<App/>);
